{"name": "test_fail", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 0", "trace": "self = <test_say_hi.TestSayHi object at 0x000001875D050370>\n\n    @pytest.mark.xfail(True, reason=\"\")\n    @allure.step(title=\"断言失败--打印文字\")\n    def test_fail(self):\n        print(\"hi, fail!!!\")\n>       assert 0\nE       assert 0\n\nscripts_all\\test_say_hi.py:16: AssertionError"}, "steps": [{"name": "断言失败--打印文字", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0\n", "trace": "  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\27632\\PycharmProjects\\Jenkins_pytest\\scripts_all\\test_say_hi.py\", line 16, in test_fail\n    assert 0\n"}, "start": 1685431251333, "stop": 1685431251333}], "start": 1685431251333, "stop": 1685431251333, "uuid": "5898c4f5-4f2b-4665-b0f3-4f3ced9ccea5", "historyId": "647861b137ae27401e520c32e07e53f2", "testCaseId": "c3b4e0252120a075c9f1e3e111261992", "fullName": "scripts_all.test_say_hi.TestSayHi#test_fail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(True, reason='')"}, {"name": "parentSuite", "value": "scripts_all"}, {"name": "suite", "value": "test_say_hi"}, {"name": "subSuite", "value": "TestSayHi"}, {"name": "host", "value": "DESKTOP-3II4BFM"}, {"name": "thread", "value": "20496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts_all.test_say_hi"}]}